name: Validate assets and data

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci || npm install --no-audit --no-fund

      - name: Case consistency check
        run: npm run check-case-consistency

      - name: Healthcheck (informational)
        run: npm run healthcheck --silent || true
